# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

updateBranch: true
deleteBranchAfterMerge: true
maxRequestedChanges:
  NONE: 0
blockingLabels:
- blocked
blockingTitleRegex: '\bWIP\b'
rules:
  - minApprovals:
      CONTRIBUTOR: 1
  - requiredLabels:
      - habx-automerge
  # APP-11930: Automatically merging pre-1.0.0 dependencies
  - requiredBodyRegex: 'because this dependency is pre-1.0.0'
